spring:
   application:
      name: lbgateway

   cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
  

      routes:
        - id: lbservice-route
          uri: lb://LBSERVICE
          predicates:
          - Path=/test/**     
      
      
server:
   port: 9999
   
management:
  endpoint:
    gateway:
      enabled: true   
   
